version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore aws-ci-cd.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output aws-ci-cd.csproj
artifacts:
  files:
    - build_output/**/*
    - scripts/**/*
    - appspec.yml