version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore src/aws-ci-cd.csproj
      - dotnet restore tests/tests.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output src/aws-ci-cd.csproj
      - dotnet publish -c release -o ./test_output tests/tests.csproj
artifacts:
  files:
    - src/build_output/**/*
    - scripts/**/*
    - appspec.yml